version: "3.8"

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"

  processor:
    build: ./processor_service
    runtime: nvidia
    environment:
      S3_ENDPOINT: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      S3_BUCKET: my-bucket
      ZIP_KEY: uploads/test.zip
      OUTPUT_PREFIX: results/
    depends_on:
      - minio
    volumes:
      - ./checkpoints:/workspace/ml-matrix3d/checkpoints
